monolog:
    channels:
        - task
        - deprecation

when@dev:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: warning
                channels: ["!event", "!task"]
                max_files: 10
            task:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.task.log"
                level: info
                channels: ["task"]
                max_files: 10
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            task:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.task.log"
                level: info
                channels: ["task"]
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: warning
                channels: ["!event", "!task"]
                max_files: 30
            task:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.task.log"
                level: info
                channels: ["task"]
                max_files: 30
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr

