services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Newageerp\SfKeyValue\SfKeyValueService:
    arguments: [ ]
  Newageerp\SfShedulledTask\SfShedulledTaskLogTask:
    arguments: [ ]

  # repo
  Newageerp\SfEntity\Repository\:
    resource: '../SfEntity/Repository/*'
    arguments: [ ]
  # repo end

  Newageerp\SfStatus\Service\StatusService:
    arguments: [ ]
  Newageerp\SfSummary\SfSummaryController:
    arguments: [ ]
  Newageerp\SfSummary\SfSummaryService:
    arguments: [ ]

  Newageerp\SfAuth\Controller\AuthController:
    arguments: [ ]
  Newageerp\SfAuth\Service\AuthService:
    arguments: [ ]
  Newageerp\SfApps\Controller\ProxyController:
    arguments: [ ]
  
  Newageerp\SfInit\Controller\InitController:
    arguments: [ ]

  Newageerp\SfControlpanel\Controller\:
    resource: '../SfControlpanel/Controller/*'
    arguments: [ ]
  Newageerp\SfControlpanel\Service\:
    resource: '../SfControlpanel/Service/*'
    arguments: [ ]
  Newageerp\SfControlpanel\Console\PropertiesUtils:
    arguments: [ ]
  Newageerp\SfControlpanel\Console\PropertiesUtilsV3:
    arguments: [ ]
  Newageerp\SfControlpanel\Console\EntitiesUtilsV3:
    arguments: [ ]
  Newageerp\SfTabs\Service\SfTabsService:
    arguments: [ ]
  Newageerp\SfControlpanel\Console\EditFormsUtilsV3:
    arguments: [ ]
  Newageerp\SfControlpanel\Console\ViewFormsUtilsV3:
    arguments: [ ]
  Newageerp\SfControlpanel\Console\PdfsUtilsV3:
    arguments: [ ]

  Newageerp\SfConfig\Service\ConfigService:
    arguments: [ ]
  Newageerp\SfConfig\Controller\SfConfigController:
    arguments: [ ]

  Newageerp\SfControlpanel\Console\Maker\MakePluginWithServiceAndMessageHandler:
    tags:
      - { name: 'console.command' }

  Newageerp\SfControlpanel\Console\In\:
    resource: '../SfControlpanel/Console/In/*'
    tags:
      - { name: 'console.command' }

  Newageerp\SfControlpanel\Console\Out\:
    resource: '../SfControlpanel/Console/Out/*'
    tags:
      - { name: 'console.command' }

  Newageerp\SfCurrency\Service\CurrencyService:
    arguments: [ ]
  Newageerp\SfCurrency\Controller\CurrencyController:
    arguments: [ ]

  Newageerp\SfEventListener\EventListener\OnFlushEventListener:
    arguments: [ ]
    tags:
      - name: "doctrine.event_listener"
        event: "onFlush"
        priority: 900
        connection: "default"
      - name: "doctrine.event_listener"
        event: "postFlush"
        priority: 900
        connection: "default"
  Newageerp\SfEventListener\Controller\EventListenerController:
    arguments: [ ]

  Newageerp\SfExport\Controller\ExportController:
    arguments: [ ]

  Newageerp\SfFiles\Controller\FilesController:
    arguments: [ ]
  Newageerp\SfFiles\Service\FileService:
    arguments: [ ]

  Newageerp\SfFollowUp\Controller\FollowUpController:
    arguments: [ ]

  Newageerp\SfImport\Controller\ImportController:
    arguments: [ ]

  Newageerp\SfMailSmtp\Service\SmtpSendMailService:
    arguments: [ ]

  Newageerp\SfMailjet\Service\MailjetSendMailService:
    arguments: [ ]
  Newageerp\SfMailjet\Service\MailjetService:
    arguments: [ ]

  Newageerp\SfMail\Controller\MailController:
    arguments: [ ]

  Newageerp\SfNotes\Controller\NotesController:
    arguments: [ ]
  Newageerp\SfNotes\Messenger\NotesReadAllMessageHandler:
    tags: [ messenger.message_handler ]

  Newageerp\SfPdf\Controller\PdfController:
    arguments: [ ]

  Newageerp\SfPushMessages\Service\FirebasePushService:
    arguments: []

  Newageerp\SfReactTemplates\StaticEvents\:
    resource: '../SfReactTemplates/StaticEvents/*'
    arguments: [ ]


  Newageerp\SfReactTemplates\CoreTemplates\:
    resource: '../SfReactTemplates/CoreTemplates/*'
    arguments: [ ]
  Newageerp\SfReactTemplates\Template\:
    resource: '../SfReactTemplates/Template/*'
    arguments: [ ]
  Newageerp\SfReactTemplates\Controller\:
    resource: '../SfReactTemplates/Controller/*'
    arguments: [ ]

  Newageerp\SfSerialNumber\Service\SerialNumberService:
    arguments: [ ]


  Newageerp\SfSocket\Service\SocketService:
    arguments: [ ]
  Newageerp\SfSocket\Service\WsUpdateService:
    arguments: [ ]

  Newageerp\SfStatus\Controller\StatusController:
    arguments: [ ]


  Newageerp\SfUservice\Service\UService:
    arguments: [ ]
  Newageerp\SfUservice\Controller\UController:
    arguments: [ ]
  Newageerp\SfUservice\EventListener\OnFlushEventListener:
    arguments: [ ]
    tags:
      - name: "doctrine.event_listener"
        event: "onFlush"
        priority: 900
        connection: "default"
      - name: "doctrine.event_listener"
        event: "postFlush"
        priority: 900
        connection: "default"


  Newageerp\SfXlsx\Controller\XlsxController:
    arguments: [ ]
  Newageerp\SfXlsx\Service\XlsxService:
    arguments: [ ]


  Newageerp\SfReactTemplates\Console\InstallTemplates:
    tags:
      - { name: 'console.command' }


  plugins_evt_service:
    namespace: App\Plugins\
    resource: "%kernel.project_dir%/src/Plugins/**/*ListenerEvt"
    tags:
      - {name: "kernel.event_listener"}
  template_evt_service:
    namespace: App\Template\
    resource: "%kernel.project_dir%/src/Templates/**/*TemplateEvt"
    tags:
      - {name: "kernel.event_listener"}


  Newageerp\SfSocket\EventListener\SfWsUpdateListener:
    tags:
      - {name: "kernel.event_listener"}
  Newageerp\SfSocket\EventListener\SfSocketListener:
    tags:
      - name: "doctrine.event_listener"
        event: "postPersist"
        priority: 600
        connection: "default"
      - name: "doctrine.event_listener"
        event: "postUpdate"
        priority: 600
        connection: "default"
      - name: "doctrine.event_listener"
        event: "postRemove"
        priority: 600
        connection: "default"
  Newageerp\SfAuth\Templates\UserTemplateEvt:
    tags:
      - {name: "kernel.event_listener"}